### ISSUE TITLE
Preparación del proyecto

### ISSUE THREAD

**Issue by MERJ-FI** [MERJ-FI/CANSAT#4]
Preparar el proyecto mediante el diagrama de arquitectura, para cada uno de los 3 microcontroladores.

Por hacer:

- [x] Crear la arquitectura de cada uno de los 3 micros.
- [x] Crear directorios y archivos según arquitectura.
- [x] Instalar drivers correspondientes.
- [x] Crear componentes de software.
- [x] Configurar clock, time, spi, uart, etc con parámetros adecuados.

Se considerará terminado este Issue una vez que la generación del código no tenga errores en los 3 micros.

**Comment by MERJ-FI** [comment]
Se agregaron drivers según los periféricos a usar, puede que falten algunos. Si es así se agregarán al momento de realizar la siguiente tarea.
La carpeta de donde se obtienen se crea al hacer un nuevo proyecto, que es cuando se descarga el firmware. Se ubica en "C:\Users\user\STM32Cube\Repository\STM32Cube_FW_F4_V1.27.0".

**Comment by MERJ-FI** [comment]
Se creó la configuración de Clock para los 3 micros a la máxima frecuencia y se eliminaron los drivers innecesarios en 089d9eead7d8096a19bc251b578eb4e693f646da.
@RaulVargasVIII  Cómo la beisbol?

**Comment by RaulVargasVIII** [comment]
Buen día ing, lo veo re bien. Ya había revisado los elementos en días anteriores. Hoy veré a Aldo para probar las antenas (y)

**Comment by MERJ-FI** [comment]
Se terminó de agregar la configuración de GPIOs. Quedan pendientes algunas cosas como la función alternativa en el STM32F103 y uno que otro detalle en el modo de los pines SPI.

**Comment by MERJ-FI** [comment]
En commit 54948f6c8e84dbe473502687fd1dd11f8225da63:
El scheduler está agregado. Se hizo la tarea Idle como prueba para hacer parpadear un LED.
Falta agregar las demás tareas y fijar los periodos de las mismas. Posiblemente se suba la hoja de excel usada para la planeación de las anteriores.

@RaulVargasVIII  Ing Brambila, si tiene la blackpill favor de descargar el programa correspondiente para hacer validación de la tarea Idle. Si necesita una introducción a la estructura y funcionamiento del proyecto me avisa.

**Comment by MiguelNarv** [comment]
En commit e5478bd4f86eb3b480cf1e434168505f83da8510:
Queda pendiente integrar los periféricos en los 3 micros y probar.

**Comment by MiguelNarv** [comment]
En 0ca03cb32f4680f03f2766801ac166728bd7d804:

Se agregó el código de periféricos.
Queda pendiente carga secundaria y USB en adquisición.
